language: ruby
before_install:
  - gem update bundler
rvm:
  - '1.9.3'
  - '2.0.0'
  - '2.1.10'
  - '2.2.10'
  - '2.3.8'
  - '2.4.9'
  - '2.5.7'
  - '2.6.5'
  - '2.7.0'
gemfile:
  - gemfiles/rspec_2.gemfile
  - gemfiles/rspec_3.gemfile
